name: send_message.yaml CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>${{ github.workflow }}</b>

            <b>${{ github.actor }}</b> сделал коммит в <code>master</code>.
            <b>Сообщение к коммиту:</b> <code>${{ github.event.commits[0].message }}</code>
            <b>Репозиторий:</b> <code>${{ github.repository }}</code>

            <a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">Изменения</a>

            <a href="http://${{ secrets.HOST }}/redoc/">Проверить что не упал прод</a>
